language: python
env:
  - TESTING = 'true'
python:
  - "3.6"

install:
  - source API/.env
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE stackoverflow_lite' -U postgres
  - psql -c "CREATE USER rickynyairo WITH PASSWORD 'aces4890';" -U postgres
  - psql -f stackovflow.sql stackoverflow_lite
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE stackoverflow_lite to rickynyairo;" -U postgres

script:
  - nosetests API/app/tests -v --with-coverage --cover-package=app

after_success:
  - coveralls
