env:
  global:
    - CC_TEST_REPORTER_ID=cc18841fb954f8377e0b450f6552580b43e03156af3677df6d7dbf02975fd588
matrix:
  include:    
    - language: python
      python:
        - "3.6"
      
      install:
        - pip install -r requirements.txt
        - pip install coveralls
      
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build

      script:
        - nosetests API/app/tests -v --with-coverage --cover-package=app
      
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

      after_success:
        - coveralls
