language: python
python:
  - "3.6"

install:
  - source API/.env
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE stackoverflow_lite' -U postgres
  - psql -c 'CREATE USER rickynyairo WITH PASSWORD aces4890;' -U postgres

script:
  - nosetests API/app/tests -v --with-coverage --cover-package=app

after_success:
  - coveralls
